language: ruby
cache: bundler
branches:
  only:
    - master
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

install: gem install test-unit mocha net-ssh
script: rake test
